version: '3'
volumes:
  pip-store:
services:
  flask:
    build: ./docker/python
    container_name: flask_container
    tty: true
    links:
      - redis
    ports:
      - 8000:3031
    volumes:
      - ./:/var/www
      - pip-store:/root/opt
  celery:
    build: ./docker/python
    container_name: celery_container
    tty: true
    links:
      - redis
    volumes:
      - ./:/var/www
      - pip-store:/root/opt
    command: celery -A src.job:job worker --loglevel=info
    depends_on:
      - flask
      - redis
  nginx:
    build: ./docker/nginx
    container_name: nginx_container
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/tmp/nginx_log:/var/log/nginx
    links:
      - flask
    ports:
      - 8001:80
    environment:
      TZ: "Asia/Tokyo"
  redis:
    image: redis:6.2.2
    container_name: broker_container
    ports:
      - "6379:6379"
    command: redis-server